### ISSUE TITLE
path/to/train

### ISSUE THREAD

**Issue by liuyueChang** [AutoVision-cloud/SSL-Lanes#3]
Thank you for your outstanding work

I would like to ask for the command mentioned in readme
`horovodrun -np 4 -H localhost:4 python /path/to/train.py -m lanegcn`

In this command,/path/to/train.py refers to which train.py in the warehouse, and I am not quite sure about the role of each folder. Thank you sincerely, if you can answer my question

**Comment by hahei12345** [comment]
You can switch to the folder you want to run and run directly  "horovodrun -np 4 -H localhost:4 python train.py -m lanegcn"
